name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - 'client/**'
      - 'seller-dashboard/**'
      - 'server/**'

jobs:
  build-client:
    if: contains(github.event.head_commit.message, 'client')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client Docker image
        run: |
          cd client
          docker build -t yourdockerhubusername/client:${{ github.sha }} .
          docker push yourdockerhubusername/client:${{ github.sha }}

  build-seller-dashboard:
    if: contains(github.event.head_commit.message, 'seller-dashboard')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push seller-dashboard Docker image
        run: |
          cd seller-dashboard
          docker build -t yourdockerhubusername/seller-dashboard:${{ github.sha }} .
          docker push yourdockerhubusername/seller-dashboard:${{ github.sha }}

  build-server:
    if: contains(github.event.head_commit.message, 'server')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server Docker image
        run: |
          cd server
          docker build -t yourdockerhubusername/server:${{ github.sha }} .
          docker push yourdockerhubusername/server:${{ github.sha }}
