name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
    paths:
      - 'client/**'
      - 'seller-dashboard/**'
      - 'server/**'
  pull_request:
    branches:
      - main  
    paths:
      - 'client/**'
      - 'seller-dashboard/**'
      - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Detect changed folders
        id: changed_folders
        run: |
          echo "server=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^server/' && echo true || echo false)" >> "$GITHUB_OUTPUT"
          echo "client=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^client/' && echo true || echo false)" >> "$GITHUB_OUTPUT"
          echo "seller_dashboard=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^seller-dashboard/' && echo true || echo false)" >> "$GITHUB_OUTPUT"

      - name: Build and push client Docker image
        if: ${{steps.changed_folders.outputs.client}} == 'true'
        run: |
          cd client
          docker build -t rishabhraghwendra18/spring-bazaar-client:${{ github.sha }} .
          docker push rishabhraghwendra18/spring-bazaar-client:${{ github.sha }}

      - name: Build and push seller-dashboard Docker image
        if: steps.changed_folders.outputs.seller_dashboard == 'true'
        run: |
          cd seller-dashboard
          docker build -t rishabhraghwendra18/spring-bazaar-seller-dashboard:${{ github.sha }} .
          docker push rishabhraghwendra18/spring-bazaar-seller-dashboard:${{ github.sha }}
        
      - name: Build and push server Docker image
        if: steps.changed_folders.outputs.server == 'true'
        run: |
          cd server
          ./mvnw clean install
          docker build -t rishabhraghwendra18/spring-bazaar-server:${{ github.sha }} .
          docker push rishabhraghwendra18/spring-bazaar-server:${{ github.sha }}